-- MySQL Script generated by MySQL Workbench
-- Thu Jul 13 19:50:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


CREATE DATABASE IF NOT EXISTS F1;
USE F1;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- DROP DATABASE F1;
-- -----------------------------------------------------
-- Table `Carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carro` (
  `idCarro` INT NOT NULL,
  `nome_modelo` VARCHAR(30) NOT NULL,
  `marca_motor` VARCHAR(30) NOT NULL,
  `idEquipe` INT NOT NULL,
  PRIMARY KEY (`idCarro`),
  UNIQUE INDEX `nome_modelo_UNIQUE` (`nome_modelo` ASC) VISIBLE,
  INDEX `fk_Carro_Equipe1_idx` (`idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Carro_Equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `Equipe` (`idEquipe`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(50) NOT NULL,
  `pais` VARCHAR(30) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `bairro` VARCHAR(60) NULL,
  `numero` INT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `idEquipe` INT NOT NULL,
  PRIMARY KEY (`idEndereco`, `idEquipe`),
  INDEX `fk_Endereco_Equipe1_idx` (`idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `Equipe` (`idEquipe`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Engenheiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Engenheiro` (
  `area_trab` VARCHAR(50) NOT NULL,
  `idEngenheiro` INT NOT NULL,
  PRIMARY KEY (`idEngenheiro`),
  CONSTRAINT `fk_Engenheiro_Funcionario1`
    FOREIGN KEY (`idEngenheiro`)
    REFERENCES `Funcionario` (`idFuncionario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Equipe` (
  `idEquipe` INT NOT NULL AUTO_INCREMENT,
  `nomeEquipe` VARCHAR(50) NOT NULL,
  `titulos` INT NOT NULL,
  `ano_adesao` INT NOT NULL,
  PRIMARY KEY (`idEquipe`),
  UNIQUE INDEX `nomeEquipe_UNIQUE` (`nomeEquipe` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fa` (
  `idFa` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `num` INT NOT NULL,
  `bairro` VARCHAR(60) NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `pais` VARCHAR(30) NOT NULL,
  `logradouro` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idFa`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Funcionario` (
  `idFuncionario` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `nacionalidade` VARCHAR(30) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `tipo_func` CHAR(1) NOT NULL,
  `ano_contratacao` INT NOT NULL,
  `idEquipe` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  INDEX `fk_Funcionario_Equipe1_idx` (`idEquipe` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `Equipe` (`idEquipe`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Inovacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Inovacao` (
  `idInovacao` INT NOT NULL AUTO_INCREMENT,
  `nome_inovacao` VARCHAR(50) NOT NULL,
  `idEngenheiro` INT NOT NULL,
  PRIMARY KEY (`idInovacao`),
  UNIQUE INDEX `nome_inovacao_UNIQUE` (`nome_inovacao` ASC) VISIBLE,
  INDEX `fk_Inovacao_Engenheiro1_idx` (`idEngenheiro` ASC) VISIBLE,
  CONSTRAINT `fk_Inovacao_Engenheiro1`
    FOREIGN KEY (`idEngenheiro`)
    REFERENCES `Engenheiro` (`idEngenheiro`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Patrocinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Patrocinador` (
  `idPatrocinador` INT NOT NULL AUTO_INCREMENT,
  `nome_patro` VARCHAR(50) NOT NULL,
  `pais_origem` VARCHAR(50) NOT NULL,
  `setor_comercial` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idPatrocinador`),
  UNIQUE INDEX `nome_patro_UNIQUE` (`nome_patro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Patrocinador_Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Patrocinador_Equipe` (
  `idPatrocinador` INT NOT NULL,
  `idEquipe` INT NOT NULL,
  PRIMARY KEY (`idPatrocinador`, `idEquipe`),
  INDEX `fk_Patrocinador_has_Equipe_Equipe1_idx` (`idEquipe` ASC) VISIBLE,
  INDEX `fk_Patrocinador_has_Equipe_Patrocinador_idx` (`idPatrocinador` ASC) VISIBLE,
  CONSTRAINT `fk_Patrocinador_has_Equipe_Patrocinador`
    FOREIGN KEY (`idPatrocinador`)
    REFERENCES `Patrocinador` (`idPatrocinador`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Patrocinador_has_Equipe_Equipe1`
    FOREIGN KEY (`idEquipe`)
    REFERENCES `Equipe` (`idEquipe`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piloto` (
  `titulos` INT NOT NULL,
  `pole_position` INT NOT NULL,
  `vitorias` INT NOT NULL,
  `pontos` INT NOT NULL,
  `n_corridas` INT NOT NULL,
  `idPiloto` INT NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`idPiloto`),
  UNIQUE INDEX `pontos_UNIQUE` (`pontos` ASC) VISIBLE,
  UNIQUE INDEX `n_corridas_UNIQUE` (`n_corridas` ASC) VISIBLE,
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC) VISIBLE,
  CONSTRAINT `fk_Piloto_Funcionario1`
    FOREIGN KEY (`idPiloto`)
    REFERENCES `Funcionario` (`idFuncionario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Piloto_Fa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Piloto_Fa` (
  `idPiloto` INT NOT NULL,
  `idFa` INT NOT NULL,
  PRIMARY KEY (`idPiloto`, `idFa`),
  INDEX `fk_Piloto_has_Fã_Fã1_idx` (`idFa` ASC) VISIBLE,
  INDEX `fk_Piloto_has_Fã_Piloto1_idx` (`idPiloto` ASC) VISIBLE,
  CONSTRAINT `fk_Piloto_has_Fã_Piloto1`
    FOREIGN KEY (`idPiloto`)
    REFERENCES `Piloto` (`idPiloto`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Piloto_has_Fã_Fã1`
    FOREIGN KEY (`idFa`)
    REFERENCES `Fa` (`idFa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

